"use client";

import { useState } from "react";
import {
  SparklesIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ShieldExclamationIcon,
} from "@heroicons/react/24/outline";
import { Card } from "@/components/Card";
import type { EvaluationResults } from "@/lib/api";

interface RecommendationPanelProps {
  results: EvaluationResults;
}

export function RecommendationPanel({ results }: RecommendationPanelProps) {
  const [expandedVendor, setExpandedVendor] = useState<string | null>(null);

  const paragraphs = results.recommendation
    .split("\n")
    .map((p) => p.trim())
    .filter((p) => p.length > 0);

  return (
    <div className="space-y-6">
      {/* ─── AI Recommendation ─────────────────────────────────────── */}
      <Card className="!bg-gradient-to-br !from-orange-50 !to-white !border-orange-200">
        <div className="flex items-start gap-3 mb-4">
          <div className="flex-shrink-0 w-10 h-10 rounded-full bg-primary-500 flex items-center justify-center">
            <SparklesIcon className="w-6 h-6 text-white" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-gray-900">
              AI Recommendation
            </h2>
            <p className="text-xs text-gray-500 mt-0.5">
              Generated by Qwen AI based on the evaluation criteria
            </p>
          </div>
        </div>

        <div className="prose prose-sm max-w-none space-y-3 text-gray-800 leading-relaxed">
          {paragraphs.length === 0 ? (
            <p className="italic text-gray-500">
              No recommendation generated.
            </p>
          ) : (
            paragraphs.map((para, i) => <p key={i}>{para}</p>)
          )}
        </div>
      </Card>

      {/* ─── Risk Comparison Summary ──────────────────────────────── */}
      <Card>
        <h2 className="flex items-center gap-2 text-lg font-semibold text-gray-900 mb-4">
          <ShieldExclamationIcon className="w-5 h-5 text-red-500" />
          Risk Comparison Summary
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {results.vendors.map((v) => (
            <div
              key={v.vendor_name}
              className="p-4 border border-gray-200 rounded-lg"
            >
              <h3 className="font-medium text-gray-900 mb-2">
                {v.vendor_name}
              </h3>
              {v.risks.length === 0 ? (
                <p className="text-sm text-gray-500 italic">
                  No significant risks identified.
                </p>
              ) : (
                <ul className="space-y-1.5">
                  {v.risks.map((r, i) => (
                    <li
                      key={i}
                      className="text-sm text-gray-700 flex gap-2 items-start"
                    >
                      <span className="text-red-500 mt-1">●</span>
                      <span>{r}</span>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          ))}
        </div>
      </Card>

      {/* ─── Follow-Up Questions ──────────────────────────────────── */}
      <Card>
        <h2 className="text-lg font-semibold text-gray-900 mb-4">
          Suggested Follow-Up Questions
        </h2>
        <div className="space-y-2">
          {Object.entries(results.follow_up_questions).map(
            ([vendor, questions]) => {
              const isOpen = expandedVendor === vendor;
              return (
                <div
                  key={vendor}
                  className="border border-gray-200 rounded-lg overflow-hidden"
                >
                  <button
                    onClick={() =>
                      setExpandedVendor(isOpen ? null : vendor)
                    }
                    className="w-full flex items-center gap-2 p-3 hover:bg-gray-50 text-left"
                  >
                    {isOpen ? (
                      <ChevronDownIcon className="w-4 h-4 text-gray-400" />
                    ) : (
                      <ChevronRightIcon className="w-4 h-4 text-gray-400" />
                    )}
                    <span className="font-medium text-gray-800">{vendor}</span>
                    <span className="ml-auto text-xs text-gray-500">
                      {questions.length} question{questions.length !== 1 && "s"}
                    </span>
                  </button>
                  {isOpen && (
                    <div className="px-4 pb-4 pt-2 bg-gray-50 border-t border-gray-200">
                      <ol className="list-decimal list-inside space-y-2 text-sm text-gray-700">
                        {questions.map((q, i) => (
                          <li key={i}>{q}</li>
                        ))}
                      </ol>
                    </div>
                  )}
                </div>
              );
            }
          )}
        </div>
      </Card>

      {/* ─── Footer ───────────────────────────────────────────────── */}
      <p className="text-center text-xs text-gray-400 italic">
        This evaluation was generated by Qwen AI. Results should be reviewed by
        procurement professionals.
      </p>
    </div>
  );
}
